# Generated by Django 3.2.8 on 2021-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(to='API.Player'),
        ),
    ]
